import pandas as pd
import numpy as np


dtype_voted = pd.CategoricalDtype(['A', 'P', 'Y'])

voters_dtypes = dict(vanid=np.uintc,
                     Age=np.half,
                     Sex=pd.CategoricalDtype(['F', 'M', 'U']),
                     Party=pd.CategoricalDtype(['D ', 'U ', 'G ', 'R ', 'I ', 'L ', 'O ']),
                     PrecinctName=pd.CategoricalDtype(['L. P. Wilson',
                        'John F Kennedy School', '330 Windsor Avenue', 'Windsor Town Hall',
                        'Oliver Ellsworth School', 'Poquonock School', 'Rainbow Firehouse'],
                        ordered=True),
                     General20=dtype_voted, General18=dtype_voted, General16=dtype_voted, General14=dtype_voted, General12=dtype_voted, General10=dtype_voted, General08=dtype_voted, General06=dtype_voted, General04=dtype_voted, General02=dtype_voted, General00=dtype_voted, Municipal21=dtype_voted, Municipal19=dtype_voted, Municipal17=dtype_voted, Municipal15=dtype_voted, Municipal13=dtype_voted, Municipal11=dtype_voted, Municipal09=dtype_voted, Municipal07=dtype_voted, Municipal05=dtype_voted, Municipal03=dtype_voted, MunicipalPrimary21=dtype_voted, MunicipalPrimarys=dtype_voted, MunicipalPrimary19=dtype_voted, MunicipalPrimary17=dtype_voted, MunicipalPrimary15=dtype_voted, MunicipalPrimary13=dtype_voted, MunicipalPrimary13Party=dtype_voted, MunicipalPrimary11=dtype_voted, PresidentialPrimary16=dtype_voted, PresidentialPrimary12=dtype_voted, PresidentialPrimary08=dtype_voted, PresidentialPrimary08Party=dtype_voted, Primarys=dtype_voted, Primary19=dtype_voted, Primary18=dtype_voted, Primary16=dtype_voted, Primary14=dtype_voted, Primary12=dtype_voted, Primary10=dtype_voted, Primary06=dtype_voted, Special21=dtype_voted, Specials=dtype_voted, Special19=dtype_voted, Special18=dtype_voted, Special17=dtype_voted, Special11=dtype_voted,
                     s18DNCDemSupport=np.half, CivGOTV=np.half, CivPart18=np.half,
                     CivRace=pd.CategoricalDtype(['White-High', 'Black-Low', 'Black-Medium', 'White-Low',
                                                  'White-Medium', 'Black-High', 'Latinx-Low', 'Asian-Medium',
                                                  'Asian-High', 'Latinx-Medium', 'Latinx-High', 'Asian-Low',
                                                  'Native American-Low']),
                     CivTnt=np.half, Tnt=np.half,
                     s18TSMEth=pd.CategoricalDtype(['Caucasian', 'Uncoded', 'African-American', 'Asian', 'Hispanic', 'Native American']),
                     s18TSMMdGnTNT=np.half, s18TSMNatPart=np.half, s18TSMNPYPT=np.half, DLCCHDSup=np.half, DLCCSDSup=np.half, DLCCTurnout=np.half, EconomyPersuasion=np.half, GunViolencePreventio=np.half, HealthcarePersuasion=np.half, CivPart20=np.half, TrumpPersuasion=np.half, YEARXXScoreSName=np.half, DemPartySup=np.half, DemPartySup2=np.half, NatTO=np.half, PrChc=np.half, s20CivKidsinHH=np.half, s20CivMarriage=np.half, CivSpan=np.half, s20VolProp=np.half, TrumpDisapprov=np.half,
                     Address="string", Zip5="string", Zip4="string"
                     )

contact_dtypes = dict(vanid=np.uintc,
                      ResultShortName=pd.CategoricalDtype(['Canvassed', 'Not Home', 'Refused', 'Wrong Number', 'Left Message',
                                                           'Call Back', 'Busy', 'Disconnected', 'Moved', 'Not Interested',
                                                           'Do Not Text', 'Come Back', 'Hostile', 'Deceased', 'Vacant',
                                                           'Other Language']),
                      CanvassedBy="string",
                      ContactTypeName=pd.CategoricalDtype(['Phone', 'Walk', 'SMS Text', 'Event', 'No Actual Contact']),
                     )

survey_dtypes = dict(vanid=np.uintc,
                     SurveyQuestionId=np.uintc,
                     SurveyResponseId=np.uintc,
                     Cycle=np.uintc,
                     SurveyQuestionType=pd.CategoricalDtype(['Candidate', 'Issue', 'Action']),
                     SurveyQuestionLongName=pd.CategoricalDtype(['MSQ2010 US Senator', 'Canty2012ID', '2014 Governor',
                                                                 'MSQ2010 Governor', 'Windsor budget', 'Voted Oct 2',
                                                                 '2016Windsor Budget', 'Vote by 3pm', '2017: Municipal Vote',
                                                                 'will vote', 'WinBud18', 'MSQ2010 State House',
                                                                 'MSQ2010 State Senate', 'Vote for Dems Row B', 'DemSupport',
                                                                 'Voted Aug primary', 'Windsorbudget', '2015 Budget', 'GOTV Row A',
                                                                 'Voting_Times', 'GOTV', 'MSQ2010 House of Rep',
                                                                 'HD5 Primary revote', 'Leo Canty ID', 'Garibay ID',
                                                                 'Vote for Al Simon', '2013 Windsor Budget', 'Most Important Issue',
                                                                 'Commit to vote', 'Do you know Al Simon', 'CT Dems Slate',
                                                                 '2016 President', '2019 Muni Volunteer', 'Vote for Trinks-RowB']),
                     SurveyResponseName="string", # requires further parsing
                     ContactType=pd.CategoricalDtype(['Phone', 'Walk', 'SMS Text', 'Robocall', 'Paid ID']),
                     CanvassedBy="string",
                     )

code_dtypes = dict(vanid=np.uintc,
                   ActivistCodeID=np.uintc,
                   ActivistCodeType=pd.CategoricalDtype(['Constituency', 'Legacy', 'Activist', 'Candidate', 'EDay Assignment']),
                   ActivistCodeName=pd.CategoricalDtype(['PhysicalTherap2018', '2016 Pres Supporter', 'Independent',
                                                         'Green', 'Libertarian Party', '2020 In Person', '2021 Candidates',
                                                         'Active Teacher', 'Real Estate Sales', 'Likely State Emp HH',
                                                         'State Employee HH', 'Registered Nurse', 'Advanced Practice RN',
                                                         'Active Teacher 2014', 'Party Chg UtoD', 'Active Teacher 2008',
                                                         'Speech Language Path', 'Pharmacy Technicians',
                                                         'Retired Teacher 2014', 'Dental Hygienist', 'Barber/Cosmet 2018',
                                                         'EmergResp 2016', 'Pharmacy 2018', 'Adv Pract RN 2018',
                                                         'RegisteredNurse 2018', 'Paramedic 2018', 'Active Teacher 2016',
                                                         'Retired Teacher 2016', 'Nurse Midwife 2018', 'Occ Therapist 2018',
                                                         'Real Estate 2018', 'ClinicalSocialWork18', 'Electrical 2018',
                                                         'Plumbers', 'Massage Therapists', 'Electricians',
                                                         'MastersSocialWork18', 'SpeechPathologist18',
                                                         'RealEstatePending18', 'RegisteredNurse 2020',
                                                         'Active Teacher 2020', 'Veterinarian 2020', 'RealEstateSales2020',
                                                         'AlchlDrug Couns 2020', 'Pro Counselor 2020',
                                                         'OccTherapistAsst2020', 'Clinic Soc Wkr 2020',
                                                         'Retired Teacher 2020', 'Plumbing 2020', 'Adv Pract RN 2020',
                                                         'Hairdresser 2020', 'Prac Nurse 2020', 'Electrical 2020',
                                                         'Phys/Surgeon 2020', 'Respiratory 2020', 'Chiropractor 2020',
                                                         'Massage Thrp 2020', 'Pharmacist 2020', 'Paramedic 2020',
                                                         'Pharmacy Tech 2020', 'CPA Licensee 2020', 'Tattoo Tech 2020',
                                                         'Phys Therapist 2020', 'Emg Med Tech 2020', 'DentalHygienist 2020',
                                                         'Phy Therp Asst 2020', 'Emg Med Respond 2020',
                                                         'RealEstateBroker2020', 'MLSW 2020', '2012 5HD 2nd primary',
                                                         'Windsor Budget 2009', '2013 Budget #1', '2015 Budget 1',
                                                         '2013 Budget #2', '2013 Budget #3', '2013 Budget #4',
                                                         '2016Budget2', 'May2014Budget', '2015 Budget 2', '2016Budget1',
                                                         'Windsor budget 2010', 'Windsor  budget 2011',
                                                         '2013 Bud 3 dist 1-4', 'WIndsor budget 2012',
                                                         'Windsor 2005 Budget', 'Windsor 2006 Ref. 3', 'Windsor 2004 Ref.',
                                                         'Windsor 2004 Primary', 'Windsor 2006 Ref. 1',
                                                         'Windsor 2005 Primary', '2021 Windsor Budget',
                                                         '2019 Budget Voters', '2020 DTC Member', '2015 budget 3 yes',
                                                         'Locksmith 2020', 'Radiographer 2020', 'Spch/Lang Path 2020',
                                                         'Architect 2020', 'Doctor 2018', 'Plumber 2018',
                                                         'Radiographer 2018', 'Dietician/Nutr 2018', 'Party Chg DtoU',
                                                         'MassageTherapist2018', 'Architect 2018', 'Clinical Social Work',
                                                         'CPA Certificate', 'CPA License', 'Respiratory Care Pra',
                                                         'Physical Therapist', 'Retired Teacher', 'Dental Hygienist2018',
                                                         'CPA license 2018', 'CPA certificate 2018', 'Occupational Therapi',
                                                         'OccuTherapist Assist', 'Physician Surgeon', 'Embalmer 2020',
                                                         'Barber 2020', 'Hypnotist 2018', 'Radiographer',
                                                         'Occ Therapist 2020', 'Dietitian/Nutri 2020', 'PhysicianAsst2018',
                                                         'AthleticTrainer 2018', 'Nurse Midwife', 'Veterinarians',
                                                         'Embalmer 2018', 'Elevator 2018', 'PhysTherAssistant',
                                                         'Psychologist 2018', 'Physician Asst 2020', 'Psychologist 2020',
                                                         'BehaviorAnalyst20', 'Chiropractor 2018', 'Party Chg RtoD',
                                                         'AthleticTrainer 2020', 'LEO DK list', 'Eye Doctor 2018',
                                                         'Optician', 'Dentists', 'Party Chg UtoR', 'Optician 2016',
                                                         'Dentist 2016', 'Optician 2020', 'Dentist 2020',
                                                         '2017 Budget voters', '2018 Budget voters', 'Al Simon people',
                                                         'Physician Assistant', 'Tattoo Tech 2018', 'Athletic Trainer',
                                                         'Dem Hostile', 'Needs Ride To Polls', '2020 AB App',
                                                         '2020 AB Voted', '2020 ABS Primary App', '2021 Lawn Sign',
                                                         'PartySwitcher21_R', '2020 Ind party', 'Inter Designer 2018',
                                                         'MaritalFamTherap2018', 'Veterinarian 2018', 'Mrg Fam Ther 2020',
                                                         'Electrologist 2020', 'Party Chg RtoU', 'Auto/Flat Glass 2018',
                                                         'Auto/Flat Glass 2020', 'Dietitian Nutritioni', 'Party Chg DtoR',
                                                         'Int Designer 2020', 'Comm. Assoc. Man. 18', 'Optician Apprentice',
                                                         'Chiropractors', 'Podiatrist 2020', '2020 Abs', 'Working Families',
                                                         'Audiologist 2016', 'Audiologist 2020']),
                   CanvassedBy="string",
                  )
